### PR TITLE
updating body to take byte array

### PR DESCRIPTION
**Pull request by LoganWright**
moving to byte array from string

### CODE REVIEW

**Comment by kylef** [comment]
Hi @LoganWright,

As mentioned in the README, all changes to the Nest specification *MUST* come though our NEP (Nest Enhancement Proposal) process. Especially considering this change is rather substantial.

> Some changes though are "substantial", and we ask that these be put through a bit of a design process and produce a consensus among the Nest team.

We already have [NEP 2](https://github.com/nestproject/neps/blob/master/draft/0002-streamable-bodies.md) which would already conflict with these changes, and for the reasons in NEP2, I think NEP2 would be a better option allowing these bodies to be streamable.

Please can you take a look at NEP2 and let us know what you think.

**NOTE:** *There is a reference implementation of NEP2 at [Nest#17](https://github.com/nestproject/Nest/pull/17) and [Inquiline#4](https://github.com/nestproject/Inquiline/pull/4)*

**Comment by LoganWright** [comment]
I'll close this in preference for the pull request that is up and submit an official NEP proposal for any future suggestions.  Just got a little to excited and started pushing things up everywhere :+1:

**Comment by takebayashi** [comment]
@kylef What prevents NEP-2 from being accepted? (or are there any discussions about this proposal?)

**Comment by kylef** [comment]
@takebayashi NEP 2 was becoming a little problematic while I tried to implement it in [Curassow](https://github.com/kylef/Curassow). We need to figure out how to implement it/tweak the design of NEP 2 for this to go forward.

The problems is that `next` on the payload is a mutating function, which means it's not possible to use from the RequestType/ResponseType since there is only a ["getter"](https://github.com/nestproject/Nest/pull/17/files#diff-9282f503c75d59533a663e987a48f673R17) in the design.

**Comment by czechboy0** [comment]
@kylef Wouldn't making the `PayloadType` a class protocol make sense here? I'd argue that we want reference semantics when it comes to large chunks of data, state of sending etc. That would also solve this issue.

**Pull request closed without merging**
